version: "3.8"
services:
  api:
    container_name: api
    build: .
    tty: true
    ports:
      - "3030:3030"
    volumes:
      - type: bind
        source: .
        target: /api

  postgres:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpwd
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres:
